package qq

// staticChannels is the full channel directory from window.channelInfo.channelConfig.channelNav.
// Source: audited 2026-06-15 from news.qq.com article pages.
var staticChannels = []Channel{
	{ChannelID: "news_news_home", NameCN: "首页", NameEN: "home", IsLocal: false, HasFeed: false, Link: "https://www.qq.com"},
	{ChannelID: "news_news_top", NameCN: "要闻", NameEN: "news", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_bj", NameCN: "北京", NameEN: "bj", IsLocal: true, HasFeed: true},
	{ChannelID: "news_news_fx", NameCN: "AI", NameEN: "fx", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_edu", NameCN: "教育", NameEN: "edu", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_quanyun", NameCN: "世界杯", NameEN: "quanyun", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_tech", NameCN: "科技", NameEN: "tech", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_finance", NameCN: "财经", NameEN: "finance", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_qa", NameCN: "热问", NameEN: "qa", IsLocal: false, HasFeed: true, Link: "https://news.qq.com/ch/qa"},
	{ChannelID: "news_news_world", NameCN: "国际", NameEN: "world", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_mil", NameCN: "军事", NameEN: "milite", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_ent", NameCN: "娱乐", NameEN: "ent", IsLocal: false, HasFeed: true},
	{ChannelID: "tv", NameCN: "电视剧", NameEN: "tv", IsLocal: false, HasFeed: false, Link: "https://v.qq.com/channel/tv/?ptag=qqnews"},
	{ChannelID: "news_news_sports", NameCN: "体育", NameEN: "sports", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_nba", NameCN: "NBA", NameEN: "nba", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_auto", NameCN: "汽车", NameEN: "auto", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_house", NameCN: "房产", NameEN: "house", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_antip", NameCN: "健康", NameEN: "health", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_video", NameCN: "视频", NameEN: "video", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_game", NameCN: "游戏", NameEN: "games", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_digi", NameCN: "数码", NameEN: "digi", IsLocal: false, HasFeed: true},
	{ChannelID: "variety", NameCN: "综艺", NameEN: "variety", IsLocal: false, HasFeed: false, Link: "https://v.qq.com/channel/variety/?ptag=qqnews"},
	{ChannelID: "news_news_nchupin", NameCN: "眼界", NameEN: "chupin", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_football", NameCN: "足球", NameEN: "football", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_kepu", NameCN: "科学", NameEN: "kepu", IsLocal: false, HasFeed: true},
	{ChannelID: "movie", NameCN: "电影", NameEN: "movie", IsLocal: false, HasFeed: false, Link: "https://v.qq.com/channel/movie/?ptag=qqnews"},
	{ChannelID: "news_news_esport", NameCN: "电竞", NameEN: "esport", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_history", NameCN: "历史", NameEN: "history", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_baby", NameCN: "育儿", NameEN: "baby", IsLocal: false, HasFeed: true},
	{ChannelID: "cloud_gamer", NameCN: "云游戏", NameEN: "cloud_gamer", IsLocal: false, HasFeed: false, Link: "https://gamer.qq.com/?ichannel=news_news_cloud_game"},
	{ChannelID: "news_news_lic", NameCN: "理财", NameEN: "finance_licai", IsLocal: false, HasFeed: true},
	{ChannelID: "news_news_istock", NameCN: "股票", NameEN: "finance_stock", IsLocal: false, HasFeed: true},
	{ChannelID: "ren_min_shi_pin", NameCN: "人民视频", NameEN: "ren_min_shi_pin", IsLocal: false, HasFeed: false, Link: "https://news.qq.com/omn/author/"},
	{ChannelID: "news_news_weather", NameCN: "天气", NameEN: "weather", IsLocal: false, HasFeed: false, Link: "https://tianqi.qq.com/index.htm"},
}
